name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deno:
    strategy:
      matrix:
        browser: [chromium, firefox]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Install ${{ matrix.browser }}
        run: deno run -A npm:playwright@1.47.2 install --with-deps ${{ matrix.browser }}

      - name: Run
        working-directory: ./deno
        run: deno task ${{ matrix.browser }}

  node:
    strategy:
      matrix:
        browser: [chromium, firefox]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: npm ci
        working-directory: ./node
        run: npm ci

      - name: Install Playwright Browser
        working-directory: ./node
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run
        working-directory: ./node
        run: node index.mjs ${{ matrix.browser }}
