name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deno:
    strategy:
      matrix:
        browser: [chromium, firefox]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Install ${{ matrix.browser }}
        run: deno run -A npm:playwright@1.47.2 install --with-deps ${{ matrix.browser }}

      - name: Run
        working-directory: ./deno
        run: deno task ${{ matrix.browser }}
